# Workflow derived from https://github.com/r-lib/usethis/blob/main/.github/workflows/pkgdown.yaml
on:
  push:
    branches: main
  workflow_dispatch:

name: pkgdown.yaml

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    container: bioconductor/bioconductor_docker:devel
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write

    steps:

    - uses: actions/checkout@v4

    - uses: r-lib/actions/setup-pandoc@v2

    - uses: r-lib/actions/setup-r-dependencies@v2
      with:
        cache: true
        extra-packages: any::pkgdown, any::purrr, any::knitr, any::kable, any::kableExtra, any::dplyr, local::.
        install-quarto: true
        needs: website

    - name: Build site
      run: pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)
      shell: Rscript {0}

    - name: Deploy to GitHub pages 🚀
      if: github.event_name != 'pull_request'
      uses: JamesIves/github-pages-deploy-action@v4.5.0
      with:
        clean: false
        branch: gh-pages
        folder: docs
